config/routes.rb
Rails.application.routes.draw do
  
  

root 'questions#index'

resources :questions do
  resources :comments
end

  resources :users
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :user
belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
belongs_to :user
has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
has_many :comments
has_many :questions

 validates :password, length: { minimum: 5 }
validates :password, presence: true

validates :name, presence: true
validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def current_user 
	User.where(id: session[:user_id]).first
end


helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :user_logged_in


def create
@question = Question.find(params[:question_id])

@comment = @question.comments.create(comment_params)
@comment.user = current_user
if @comment.save
	redirect_to :back
else
	redirect_to :back
end
end

private

def user_logged_in
unless current_user
	redirect_to new_session_path
end
end

def comment_params 
params.require(:comment).permit(:body)
end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 before_action :find_question, only: [:show, :edit, :update]
before_filter :current_user_presence, except: [:index, :show]
before_filter :question_belongs_to_user?, only: [:edit]

  def index
  @questions = Question.limit(20).order("created_at DESC")
  end

  def show
  end

  def edit
  end

def update
if @question.update(question_params)
  redirect_to @question
else
  render 'edit'
end
end

 def new
  @question = Question.new
  end


def create 
@question = Question.new(question_params)
@question.user = current_user
if @question.save
  redirect_to @question
  else
  render 'new' 
end
end

private

def current_user_presence
if current_user == nil
flash[:notice] = "You need to be logged in to do that"
  redirect_to root_path
end
end

def question_belongs_to_user?
if @question.user_id != current_user.id
flash[:notice] = "You can't edit that question"
  redirect_to question_path(params[:id])
end
end

def find_question
@question = Question.find(params[:id])
end

def question_params
params.require(:question).permit(:title, :body)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


def create
@user = User.find_by_email(params[:email])
if @user && @user.authenticate(params[:password])
	session[:user_id] = @user.id
redirect_to root_path
else
	render 'new'
end
end

def destroy
	session[:user_id] = nil
	redirect_to new_session_path
	end
	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
   end

def create
@user = User.new(user_params)
 if @user.save
	session[:user_id] = @user.id
	redirect_to root_path
 else
	render 'new'
 end
end


private

def user_params
	params.require(:user).permit(:name, :email, :password)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

def question_belongs_to_user?(question)
 question.user_id == current_user.id
end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@question, @question.comments.build] do |f| %>

<%= f.label :body %>
<div id="comment_area"><%= f.text_area :body %></div>
<br>
<div class="simple_button"><%= f.submit "Add Comment" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionsAndAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
<ul>
<% if current_user %>
<li><%= link_to("Log Out", session_path(current_user), method: :delete)%></li>
<% else %>
<li><%= link_to("Log In", new_session_path)%></li>
<li><%= link_to("Sign Up", new_user_path)%></li>
<% end %>
</ul>
</nav>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

<div class="form_wrapper">

<div class="form_input_wrapper"> 
<%= f.label :title %>
<br>
<%= f.text_field :title %>
</div>

<br>

<div class="form_input_wrapper"> 
<%= f.label :question %>
<br>
<%= f.text_area :body %>
</div>

</div>
<%= f.submit "Create Question", class: "button" %>

<br>

<br>
<div class="simple_button"><%= link_to "Back", :back %><div>

<% end %>

app/views/questions/edit.html.erb
<%= render "form" %>

app/views/questions/index.html.erb
<h2>Questions</h2>
<div class="left_sidebar">
<% @questions.each do |question| %>

<div class='content_box'>
<%= link_to question.title, question_path(question) %>

<span><%= truncate question.body %></span>


</div>

<% end %>
<br>
<br>
<div class="button_one"><%= link_to "Ask a Question", new_question_path %></div>
</div>

<div id="right_sidebar"> </div>
<br>
<br>
<br>
<br>

app/views/questions/new.html.erb
<%= render "form" %>

app/views/questions/show.html.erb
<div class="left_sidebar">
<div class="container">
<h3><%= @question.title %></h3>
<p>
<%= @question.body %>
</p>
<div class="simple_button"><%= link_to "Back", questions_path %></div>

<% if current_user %>
<% if current_user.id == @question.user_id %>
<div class="simple_button"><%= link_to "Update", edit_question_path(@question) %></div>
<% end %>
<% end %>
</div>
</div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<% @question.comments.each do |comment| %>
	<br>
	<div class="comment_box">
	<%= comment.body%>
	<h6>by <%= comment.user.name %></h6>
	</div>
	<% end %>
	<% if current_user %>
	<br>
<br>
<br>
	<%= render "comments/form"%>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>


<%= f.label :name %>
<br>
<%= f.text_field :name %>


<%= f.label :email %>
<br>
<%= f.email_field :email %>



<%= f.label :password %>
<br>
<%= f.password_field :password %>



<%= f.submit "Sign Up", class: "button" %>



<% end %>